= TP3. Sécuriser un Web-service
:toc:

== Objectifs

* Concevoir et implémenter un service REST _sécurisé_, avec authentification basique.
* Stocker les données d'authentification de manière sécurisée (avec chiffrement).
* Gérer plusieurs rôles utilisateur.


== Prologue : mise en place d'un Web-service sécurisé

En suivant le tutoriel de Frédéric Moal (`https://youtu.be/0D2myzV5h3A`), déployez un Web-service vide mais où la sécurité est activée (dépendances Maven).


== Un Web-service pour le suivi de projet

Vous devrez mettre en place un Web-service (dont vous disposez du modèle) sur le thème décrit ci-dessous.


=== Fonctionnalités attendues

Pour aider le suivi de projets, un professeur de Web-service décide de mettre en place une application permettant aux étudiants de poser des questions.
Les professeurs peuvent répondre aux questions ouvertes (non encore répondues).
Les étudiants peuvent alors consulter les réponses aux questions qu'ils ont posées.

Votre API devra permettre _au minimum_ les opérations suivantes :

* *Inscrire un compte* (numéro étudiant et password de l'étudiant, nom, prénom et date de naissance de l'étudiant).
Chaque étudiant est identifié par son numéro étudiant.
* Un *étudiant authentifié* (numéro étudiant/password) peut poser une question.
* Un *étudiant authentifié* (numéro étudiant/password) peut consulter ses questions auxquelles le professeur a répondu.
* Un *professeur authentifié* peut répondre à une question en attente d'une réponse.
* Un *professeur authentifié* peut récupérer toutes les questions en attente de réponses.


=== Travail à réaliser

. Dans la classe principale de votre application, vous devez nourrir votre façade avec des données.
Transformez tout d'abord votre façade en un objet _scannable_ par SpringBoot (c.-à-d. utilisez l'annotation `@Component`).
Ensuite ajoutez dans la classe principale de votre application le code suivant : 
+
[source, java]
----
public class Application {

    @Autowired
    FacadeUtilisateurs facadeUtilisateurs;

    public static void main(String[] args) {
        // ...
    }

    @Bean
    public CommandLineRunner commandLineRunner() {
        return args -> {
            facadeUtilisateurs.inscrireUtilisateur("yohan.boichut@univ-orleans.fr",
                    "monMotDePasse");
            facadeUtilisateurs.inscrireUtilisateur("gerard.menvussaa@etu.univ-orleans.fr",
                    "sonMotDePasse");
        };
    }
}
----

L'inconvénient du code ci-dessus est que les mots de passes sont stockés en clair dans la façade (ce qui est une très mauvaise idée). 
Nous avons donc besoin de chiffrer les mots de passe avant de les stocker.

En vous inspirant de la vidéo `https://youtu.be/ZYpY6TnTI8M`, en particulier vers 12mn36s,
créez un _Bean_ permettant de configurer le chiffrement.
Modifiez ainsi le morceau de programme précédent pour chiffrer les mots de passe au moment de l'appel à la façade.

*Petit conseil pratique :* Créez une classe configuration `CryptoConfig` (en utilisant l'annotation `@Config`) dans laquelle vous déclarerez votre bean.

[start=2]
. Complétez le tableau ci-dessous avec l'ensemble des URIs de votre Web-service, en précisant les paramètres entrants et sortants, le contexte d'utilisation, les statuts de retour (y compris erreurs), _etc._
+
.URIs de votre service REST
[cols="2m,1a,6a"]
|===
| URI | Méthode | Description

| /inscription
| POST
| Inscrire un utilisateur.
--
Requête::
Corps de la requête, avec numéro, mot de passe, nom, prénom et date de naissance de l'étudiant.
Réponses::
* 201 Created : L'inscription a été effectuée.
** L'entête contiendra le champ `Location` (URI de l'utilisateur inscrit).
** Le corps de la réponse (type de contenu `application/json`) contiendra, *au format JSON*, les données _non sensibles_ (i.e. tout sauf le mot de passe) de l'utilisateur nouvellement inscrit.

* 409 Conflict : Un utilisateur existe déjà avec ce numéro d'étudiant.
** Le corps de la réponse contiendra, *au format JSON*, le détail de l'erreur rencontrée (en particulier un message d'erreur précisant le problème).

_À compléter_
--

| /question
| POST
| Poser une question (en tant qu'étudiant).
--
Requête::
----
{
    "question": "Ma question"
}
----
Réponses::
* 201 Created : La question a bien été ajoutée.

_À compléter_
--

| /question/{idUser}
| GET
| Consulter les questions d'un étudiant.
--
Requête::
Pas de corps, tout est dans l'URI.
Réponses::
* 200 OK

_À compléter_
--
|===

[start=3]

. Codez votre API en utilisant Spring Boot, avec une *authentification Basic* et en vous limitant, dans un premier temps, à une représentation _InMemory_ des utilisateurs.
Cela implique que seules les personnes enregistrées dans la _base SpringSecurity_ pourront accéder au service (c.-à-d. les personnes inscrites via la configuration de l'authentification).
Par conséquent, même si vous ajoutez des personnes dans la façade, tant que ces personnes ne sont pas déclarées dans la _base SpringSecurity_, elles ne pourront pas accéder au service.
+
Nous proposons le principe suivant :
+
--
* les personnes qui ont une adresse email de la forme `...@etu.univ-orleans.fr` auront le rôle *ETUDIANT* ;
* les personnes qui ont une adresse email de la forme `...@univ-orleans.fr` auront les rôles *ENSEIGNANT* et *ETUDIANT*.
--
+
Vous pouvez vous aider des vidéos suivantes : 
+
--
* https://youtu.be/jZVdXnL0Wiw
* https://youtu.be/u-9kmMZnkyM
--
+
Vous pouvez retrouver un code équivalent sur github : *https://github.com/fredmoal/live-demo-security*

[start=4]

. Écrire un script permettant de valider votre Web-service.
Pensez à mettre un scénario où un nouvel individu s'inscrit à la plate-forme.
Montrez également que ce nouvel individu ne peut pas accéder aux fonctionnalités du Web-service,
et qu'un code 403 est retourné sur chacune des fonctionnalités.

. Évidemment, c'est très génant de ne pas pouvoir autoriser dynamiquement l'accès à de nouvelles personnes au Web-service.
Faites évoluer votre application en utilisant un `UserDetailService` permettant de faire une vraie authentification dynamique, en se basant sur les personnes enregistrées dans la façade.

Pour faire évoluer votre application, vous pouvez vous aider de la vidéo suivante : 

* https://youtu.be/ZYpY6TnTI8M

*Tips :* Pensez à commenter votre code devenu inutile dans cette nouvelle version, si vous souhaitez garder un historique de ce que vous avez fait précédemment.


=== Sources des classes métiers

Vous retrouverez ci-dessous les classes métiers (vous devrez générer les classes des exceptions utilisées) :


.Question.java
[source, java]
----
public class Question {

    private String idQuestion;
    private int idUtilisateur;
    private String libelleQuestion;
    private String reponse;

    public Question(int idUtilisateur, String question) {
        this.idUtilisateur = idUtilisateur;
        this.libelleQuestion = question;
        this.idQuestion = UUID.randomUUID().toString();
    }

    public String getIdQuestion() {
        return idQuestion;
    }

    public void setIdQuestion(String idQuestion) {
        this.idQuestion = idQuestion;
    }

    public int getIdUtilisateur() {
        return idUtilisateur;
    }

    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }

    public String getLibelleQuestion() {
        return libelleQuestion;
    }

    public void setLibelleQuestion(String libelleQuestion) {
        this.libelleQuestion = libelleQuestion;
    }

    public String getReponse() {
        return reponse;
    }

    public void setReponse(String reponse) {
        this.reponse = reponse;
    }
}
----


.Utilisateur.java
[source, java]
----
public class Utilisateur {

    private int idUtilisateur;
    private static int IDS=0;

    private String login;
    private String motDePasse;

    public Utilisateur(String login, String motDePasse) {
        this.idUtilisateur = IDS++;
        this.login = login;
        this.motDePasse = motDePasse;
    }

    public int getIdUtilisateur() {
        return idUtilisateur;
    }

    public String getLogin() {
        return login;
    }

    public boolean verifierMotDePasse(String motDePasse){
        return this.motDePasse.equals(motDePasse);
    }

    public String getMotDePasse() {
        return this.motDePasse;
    }
}
----


.FacadeApplication.java
[source, java]
----
public class FacadeApplication {

    /**
     * Questions posées par chaque utilisateur.
     * Les utilisateurs ne sont pas stockés ici ; on n'utilise que leur identifiant.
     */
    private Map<Integer, Collection<Question>> utilisateursQuestionsMap;

    /** Toutes les questions posées, identifiées par leur identifiant. */
    private Map<String, Question> questionsMap;

    public FacadeApplication() {
        utilisateursQuestionsMap = new HashMap<Integer, Collection<Question>>();
        questionsMap = new HashMap<String, Question>();
    }

    /**
     * Poser une nouvelle question.
     * @param idUtilisateur l'utilisateur posant la question
     * @param question      l'intitulé de la question
     * @return l'identifiant aléatoire de la question créée, au format String.
     */
    public String ajouterUneQuestion(int idUtilisateur, String question) {
        Question question1 = new Question(idUtilisateur, question);
        questionsMap.put(question1.getIdQuestion(), question1);

        if (utilisateursQuestionsMap.containsKey(idUtilisateur)) {
            this.utilisateursQuestionsMap.get(idUtilisateur).add(question1);
        } else {
            Collection<Question> questions = new ArrayList<>();
            questions.add(question1);
            this.utilisateursQuestionsMap.put(idUtilisateur, questions);
        }

        return question1.getIdQuestion();
    }

    /**
     * Répondre à une question.
     * @param idQuestion l'identifiant de la question à laquelle réponse
     * @param reponse    la réponse proposée
     * @throws QuestionInexistanteException s'il n'existe pas de question avec l'identifiant donné
     */
    public void repondreAUneQuestion(String idQuestion, String reponse)
            throws QuestionInexistanteException {
        if (this.questionsMap.containsKey(idQuestion)) {
            this.questionsMap.get(idQuestion).setReponse(reponse);
        } else {
            throw new QuestionInexistanteException();
        }
    }

    /**
     * Retourne l'ensemble des questions posées par tous les utilisateurs.
     * @return une collection de toutes les questions posées.
     */
    public Collection<Question> getQuestions() {
        return questionsMap.values();
    }

    /**
     * Retourne l'ensemble des questions en attente de réponse.
     * @return une collection des questions en attente de réponse.
     */
    public Collection<Question> getQuestionsSansReponses() {
        return this.questionsMap.values().stream()
            .filter(q -> Objects.isNull(q.getReponse()) || q.getReponse().isBlank())
            .collect(Collectors.toList());
    }

    /**
     * Récupère toutes les questions d'un utilisateur.
     * @param idUtilisateur l'identifiant de l'utilisateur dont on veut les questions
     * @return une collection des questions de cet utilisateur.
     * @throws UtilisateurInexistantException s'il n'existe pas d'utilisateur avec l'identifiant donné
     */
    public Collection<Question> getToutesLesQuestionsByUser(int idUtilisateur)
            throws UtilisateurInexistantException {
        if (this.utilisateursQuestionsMap.containsKey(idUtilisateur)) {
            return this.utilisateursQuestionsMap.get(idUtilisateur);
        } else {
            throw new UtilisateurInexistantException();
        }
    }

    /**
     * Récupère toutes les questions posées par un utilisateur, et qui ont reçu une réponse.
     * @param idUtilisateur l'identifiant de l'utilisateur dont on veut les questions
     * @return une collection des questions de cet utilisateur ayant reçu une réponse.
     * @throws UtilisateurInexistantException s'il n'existe pas d'utilisateur avec l'identifiant donné
     */
    public Collection<Question> getQuestionsAvecReponsesByUser(int idUtilisateur)
            throws UtilisateurInexistantException {
        if (this.utilisateursQuestionsMap.containsKey(idUtilisateur)) {
            return this.utilisateursQuestionsMap.get(idUtilisateur).stream()
                .filter(q -> Objects.nonNull(q.getReponse()) && (!q.getReponse().isBlank()))
                .collect(Collectors.toList());
        } else {
            throw new UtilisateurInexistantException();
        }
    }

    /**
     * Récupère toutes les questions posées par un utilisateur, et qui sont en attente de réponse.
     * personne n'a répondu
     * @param idUtilisateur l'identifiant de l'utilisateur dont on veut les questions
     * @return une collection des questions de cet utilisateur en attente de réponse.
     * @throws UtilisateurInexistantException s'il n'existe pas d'utilisateur avec l'identifiant donné
     */
    public Collection<Question> getQuestionsSansReponsesByUser(int idUtilisateur)
            throws UtilisateurInexistantException {
        if (this.utilisateursQuestionsMap.containsKey(idUtilisateur)) {
            return this.utilisateursQuestionsMap.get(idUtilisateur).stream()
                    .filter(q -> Objects.isNull(q.getReponse()) || q.getReponse().isBlank())
                    .collect(Collectors.toList());
        } else {
            throw new UtilisateurInexistantException();
        }
    }

    /**
     * Retourne une question posée par un utilisateur.
     * @param idUtilisateur l'identifiant de l'utilisateur dont on veut récupérer la question
     * @param idQuestion    l'identifiant de la question
     * @return la question posée.
     * @throws UtilisateurInexistantException     s'il n'existe pas d'utilisateur avec cet identifiant
     * @throws QuestionInexistanteException       s'il n'existe pas de question avec cet identifiant
     * @throws AccesIllegalAUneQuestionException si la question n'a pas été posée par cet utilisateur
     */

    public Question getQuestionByIdPourUnUtilisateur(int idUtilisateur,String idQuestion)
            throws QuestionInexistanteException, AccesIllegalAUneQuestionException,
                UtilisateurInexistantException {
        Question question = questionsMap.get(idQuestion);
        if (Objects.isNull(question)) {
            throw new QuestionInexistanteException();
        }

        Collection<Question> questionsIdUtilisateur = this.utilisateursQuestionsMap.get(idUtilisateur);
        if (Objects.isNull(questionsIdUtilisateur)) {
            throw new UtilisateurInexistantException();
        }

        if (questionsIdUtilisateur.contains(q)) {
            return question;
        } else {
            throw new AccesIllegalAUneQuestionException();
        }
    }
}
----


.FacadeUtilisateurs.java
[source, java]
----
public class FacadeUtilisateurs {

    /** Stocke l'ensemble des utilisateurs inscrits */
    private Map<String,Utilisateur> utilisateursMap;

    public FacadeUtilisateurs() {
        utilisateursMap = new HashMap<>();
    }

    /**
     * Retourne l'identifiant d'un utilisateur, d'après son login (c.-à-d. son adresse email).
     * @param login le login de l'utilisateur dont on veut l'identifiant
     * @return l'identifiant de l'utilisateur.
     * @throws UtilisateurInexistantException s'il n'existe pas d'utilisateur avec ce login
     */
    public int getUtilisateurIntId(String login) throws UtilisateurInexistantException {
        if (utilisateursMap.containsKey(login)) {
            return this.utilisateursMap.get(login).getIdUtilisateur();
        } else {
            throw new UtilisateurInexistantException();
        }
    }

    /**
     * Retourne un utilisateur, d'après son login.
     * @param login le login de l'utilisateur dont on veut l'identifiant
     * @return l'utilisateur.
     * @throws UtilisateurInexistantException s'il n'existe pas d'utilisateur avec ce login
     */
    public Utilisateur getUtilisateurByLogin(String login) throws UtilisateurInexistantException {
        return utilisateursMap.get(login);
    }

    /**
     * Inscrit un nouvel utilisateur.
     * @param login      le login de l'utilisateur (c.-à-d. son adresse email)
     * @param motDePasse le mot de passe de l'utilisateur
     * @return l'identifiant de l'utilisateur inscrit.
     * @throws LoginDejaUtiliseException si le login est déjà utilisé par un autre utilisateur
     */
    public int inscrireUtilisateur(String login, String motDePasse) throws LoginDejaUtiliseException {
        if (utilisateursMap.containsKey(login)) {
            throw new LoginDejaUtiliseException();
        } else {
            Utilisateur utilisateur = new Utilisateur(login, motDePasse);
            utilisateursMap.put(utilisateur.getLogin(), utilisateur);
            return utilisateur.getIdUtilisateur();
        }
    }

    /**
     * Vérifie si un mot de passe est correct (devient inutile dans la version finale).
     * @param login      le login de l'utilisateur
     * @param motDePasse le mot de passe à vérifier
     * @return _true_ si le mot de passe est correct, _false_ sinon.
     */
    public boolean verifierMotDePasse(String login, String motDePasse) {
        if (utilisateursMap.containsKey(login)) {
            return utilisateursMap.get(login).verifierMotDePasse(motDePasse);
        } else {
            return false;
        }
    }
}
----
